name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            compiler: dmd-latest
          - os: ubuntu-latest 
            arch: amd64
            compiler: ldc-latest
          - os: ubuntu-24.04-arm 
            arch: arm64
            compiler: ldc-latest
          - os: macos-latest
            arch: arm64
            compiler: dmd-latest
          - os: macos-latest
            arch: arm64
            compiler: ldc-latest
          - os: windows-latest
            arch: amd64
            compiler: dmd-latest
          - os: windows-latest
            arch: amd64
            compiler: ldc-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{matrix.compiler}}
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Build
        run: dub build
      - name: Test
        run: dub test
      - name: run Bench
        run: |
          dub -b release -c benchmark
          dub -b release -c benchmark -- $PWD/bench/urls.txt

  build-wasm:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest 
            arch: amd64
            compiler: ldc-latest
            sdk_target: x86_64-linux
          - os: ubuntu-24.04-arm 
            arch: arm64
            compiler: ldc-latest
            sdk_target: arm64-linux
          - os: macos-latest
            arch: arm64
            compiler: ldc-latest
            sdk_target: arm64-macos
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{matrix.compiler}}
      - name: Install wasm32-unknown-wasi-sdk
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          curl -sLO https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-${{matrix.sdk_target}}.tar.gz
          tar -xf wasi-sdk-25.0-${{matrix.sdk_target}}.tar.gz
          rm wasi-sdk-25.0-${{matrix.sdk_target}}.tar.gz
          echo "$PWD/wasi-sdk-25.0-${{matrix.sdk_target}}/bin" >> $GITHUB_PATH
          wasm32-wasi-clang -###      
      - name: Build
        run: dub build -c wasm --arch wasm32-unknown-wasi -v
