name: CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            compiler: dmd-latest
          - os: ubuntu-latest 
            arch: amd64
            compiler: ldc-latest
          - os: macos-latest
            arch: arm64
            compiler: dmd-latest
          - os: macos-latest
            arch: arm64
            compiler: ldc-latest
          - os: windows-latest
            arch: amd64
            compiler: dmd-latest
          - os: windows-latest
            arch: amd64
            compiler: ldc-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{matrix.compiler}}
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Build
        run: dub build
      - name: Linux PATH
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo cp $PWD/build/libada.so /usr/lib
      - name: Test
        run: dub test
      - name: run Bench
        run: |
          dub -b release -c benchmark
          dub -b release -c benchmark -- $PWD/bench/urls.txt
